### ISSUE TITLE
--zplg-shadow-zstyle:12: opts[(r)-e]: parameter not set

### ISSUE THREAD

**Issue by paulhybryant** [psprint/zplugin#12]
Get this error when adding a local plugin
zplug load foo

--zplg-shadow-zstyle:12: opts[(r)-e]: parameter not set
--zplg-shadow-zstyle:12: opts[(r)-e]: parameter not set

Cloned the repository at $ZPLG_PLUGINS_DIR/_local---foo

Also can we support cloning from any git repository given an url?

**Comment by psprint** [comment]
Added a fix to latest zplugin, does it help?

The any-url support is scheduled to be added.

**Comment by paulhybryant** [comment]
Yes that helped. Thanks!

**Comment by psprint** [comment]
Cool, thanks for confirmation
