### ISSUE TITLE
Should not overwrite $ZSH?! / integration with oh-my-zsh

### ISSUE THREAD

**Issue by blueyed** [psprint/zplugin#6]
I am not sure if https://github.com/psprint/zplugin/commit/00f2b6443d12456426230a7bb06dd4bd1fce6f3d should be done like this: from the commit message it looks like it is required for a specific plugin only?!

When integrating zplugin with oh-my-zsh as follows (so that it is sourced before OMZ's compinit)), this will break:

    source ~/Vcs/zplugin/zplugin.zsh
    source $ZSH/oh-my-zsh.sh

Same with using the full path to the OMZ script, because `$ZSH` is used therein.

My dotfiles are based on an older version of OMZ, so that might have changed.

What is the recommended setup in that case?
Using the manual method "after compinit"?

**Comment by psprint** [comment]
You're right, this shouldn't be done. This was when I started coding Zplugin and saw plugin `copyzshell`, which was designed for OMZ. Wanted to be a perfectionist I wanted even such simple and plain OMZ code to be supported by Zplugin. Bad idea. Does it work better now?

**Comment by blueyed** [comment]
Yes, thanks!

**Comment by psprint** [comment]
Thanks for the report!
